services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    labels:
      - "traefik.http.routers.airquality-frontend.entryPoints=websecure"
      - "traefik.http.routers.airquality-frontend.rule=Host(`airquality.projectdar.aplab.be`)"
      - "traefik.http.services.airquality-frontend.loadbalancer.server.port=5000"
      - "traefik.http.routers.airquality-frontend.tls.certresolver=letsencrypt"

    restart: always
    networks:
      - traefik

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    labels:
      - "traefik.http.routers.airquality-backend.entryPoints=websecure"
      - "traefik.http.routers.airquality-backend.rule=Host(`backendairquality.projectdar.aplab.be`)"
      - "traefik.http.services.airquality-backend.loadbalancer.server.port=5000"
      - "traefik.http.routers.airquality-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.airquality-backend.loadbalancer.server.scheme=http"  # <--- ADD THIS

    restart: always
    networks:
      - traefik

networks:
  traefik:
    external: true
